server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: app1
          uri: http://localhost:8081
          predicates:
            - Path=/app1/**
        - id: app2
          uri: http://localhost:8082
          predicates:
            - Path=/app2/**
          filters:
            - AddRequestHeader=app2-request, app2-request-header
            - AddResponseHeader=app2-response, app2-response-header

